name: Render & Publish TechDocs

on:
  push:
    # runs only when TechDocs related files are updated.
    branches: [ $default-branch ]
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'
      - 'mkdocs.yml'

jobs:
  catalog:
    # extract component information from the catalog info file
    uses: TierMobility/techdocs-workflows/.github/workflows/extract-entity-info.yml@main
    with:
      path: catalog-info.yaml
      entity_kind: Component
  techdocs:
    # render and publish techdocs
    needs: catalog
    uses: TierMobility/techdocs-workflows/.github/workflows/render-publish-s3.yml@main
    with:
      entity_name: ${{ needs.catalog.outputs.entity_name }}
      entity_namespace: ${{ needs.catalog.outputs.entity_namespace }}
      entity_kind: ${{ needs.catalog.outputs.entity_kind }}
    secrets: inherit