name: Render & Publish TechDocs from a Monorepo

on:
  push:
    # runs only when TechDocs related files are updated.
    branches: [$default-branch]
    paths:
      - "packages/**/docs/**"
      - "packages/**/mkdocs.yaml"
      - "packages/**/mkdocs.yml"

jobs:
  catalog:
    # discover catalog info files
    uses: TierMobility/techdocs-workflows/.github/workflows/discover-catalog-locations.yml@main
    with:
      package_dir: packages/
      entity_filename: catalog-info.yaml
  techdocs:
    runs-on: ubuntu-latest
    needs: catalog
    strategy:
      matrix: ${{ fromJson(needs.catalog.outputs.entity_locations) }}
    # extract component information from the catalog info file, render and publish techdocs
    steps:
      - uses: actions/checkout@v3
      - uses: TierMobility/techdocs-render-publish-action@main
        with:
          path: ${{ matrix.path }}
          entity_kind: Component
          bucket_name: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID  }}
          aws_secret_access_key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.TECHDOCS_AWS_REGION }}
